[package]
name = "nottirb/fusion-test"
description = "Experimental version of Fusion. These builds are unstable; I recommend using elttob/fusion."
license = "MIT"
authors = ["Elttob"]
version = "0.1.1-beta"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
